### ISSUE TITLE
won't lunche

### ISSUE THREAD

**Issue by EeEkKOo** [Tom4nt/Mega-Soundboard#62] opened 2023-08-25 21:16 UTC
when lunching a pop up appears and say "an error has occured while trying to load the app. This may cause unexpected behaviours. TypeError:Cannot read propreties of undefined (reading 'uuid')" and then procide to load indefinitely

 - OS and version: Windows 11
 - Mega Soundboard version: 0.6.3

**Comment by Tom4nt** [comment] 2023-08-25 22:25
I am not able to reproduce the issue, even in a fresh install. Can you send me your `Soundboards.json` located at `C:\Users\`Username`\AppData\Roaming\MegaSoundboard`? I will be able to see the names of your soundboards and sounds. ([tmsntns@gmail.com](mailto:tmsntns@gmail.com))
Thanks for the bug report.

**Comment by EeEkKOo** [comment] 2023-08-25 22:31
tanks for replying so fast but i'm new to this site and aparently it don't support .jason

**Comment by Tom4nt** [comment] 2023-08-25 22:33
No worries, you can send it to my email: [tmsntns@gmail.com](mailto:tmsntns@gmail.com).

**Comment by EeEkKOo** [comment] 2023-08-25 22:37
here is the file and tanks again for replying so fast.

_Eyko

Le sam. 26 août 2023 à 00:34, Tomás Antunes ***@***.***> a
écrit :

**Comment by Tom4nt** [comment] 2023-08-25 22:44
Sorry, I don't see any attachments. You can also use https://www.file.io/ and send me the link if you want.

**Comment by EeEkKOo** [comment] 2023-08-25 22:46
here is the dawnload link:
https://file.io/IJT2C7IPOFZL

**Comment by Tom4nt** [comment] 2023-08-25 23:09
Apparently, that file has no problems, but I am looking at the code and it is possible that the problem is in `Settings.json` (in the same folder). Can you send me that one too? Sorry for asking again.

**Comment by EeEkKOo** [comment] 2023-08-25 23:15
no worries, i forgot to mention that i successfuly lunched it the first time then closed it ( to see if it works in the background) then when i relunched it it showed the errore. i also tryed to lunch the 0.6.2 version but the same probleme occured. 
https://file.io/jV9kXDGmH6nn

**Comment by Tom4nt** [comment] 2023-08-25 23:48
Thanks for the additional info!
The error shows because your `Settings.json` file has the value of `selectedSoundboard` set to 1, which means the app is trying to select your second soundboard when it launches, but you only have 1 at the moment. I don't know how this happened though. Since the settings are saved when you close the app, it should never happen.

Do you remember the steps you took, like adding soundboards, etc...? If I find how it happens, I can track the root of the issue.

For now, you can fix this by opening `Settings.json` (can use notepad) and setting the value of `selectedSoundboard` to 0 instead of 1. Before that, please make sure the app is closed by ending any tasks related to Mega Soundboard in the Task Manager.

Thanks again for your contribution! It helped squashing a bug. :)

**Comment by EeEkKOo** [comment] 2023-08-25 23:52
yes i remember i created a new soundboard and deleted the first one that's maby the issu.
anyways tanks for helping me and replying that fast.

**Comment by EeEkKOo** [comment] 2023-08-26 00:01
it seems that it won't stay in the background too do you have a solution to that ?
otherwise i'm gonna resort to leave it open

**Comment by Tom4nt** [comment] 2023-08-26 00:10
Thanks to you, I was able to reproduce this consistently and find the root cause. This list is mainly for me:
1. Create Soundboard
2. Select new Soundboard
3. Delete first soundboard
4. Close and launch again

---

It should stay in the background if you have this↓ option enabled and *minimize* the window, not close. Close always fully closes.

![image](https://github.com/Tom4nt/Mega-Soundboard/assets/39926566/d739b79f-84e0-402c-b36a-8c9974eabbc5)

**Comment by EeEkKOo** [comment] 2023-08-26 00:12
ok, tanks you so much for the help and for replaying so fast
hope i helped other people too

**Closed** 2023-09-17 20:22 UTC
Labels: BUG
