### ISSUE TITLE
Cannot set PTT key when updating from 0.5

### ISSUE THREAD

**Issue by Noctabou** [Tom4nt/Mega-Soundboard#47] opened 2023-01-20 20:53 UTC
On this pc i used MegaSoundboard 0.5.2, and i updated to 0.6.1, but i can't bind Random sound Key nor PTT key because the file location is empty.
![image](https://user-images.githubusercontent.com/54266662/213802793-bcfb374e-aac9-4ba0-80d1-2b3056a4d4e4.png)

Steps to reproduce bug
Download 0.5.2, update to 0.6.x, try setting a key in the app settings.

Environment:
 - OS and version: Windows 11 22h2
 - Mega Soundboard version 0.6.1

**Comment by Tom4nt** [comment] 2023-01-20 22:03
You aren't supposed to be able to leave that field empty even in 0.5.2, so I don't know how that happened. I tried to reproduce but I couldn't. Anyway, I'll make it fill in automatically with the default value if empty.
For now, you can just use the default path, if you want: `C:\Users\`username`\AppData\Roaming\MegaSoundboard\Sounds`.

Thanks for the bug report! 👍

**Comment by Noctabou** [comment] 2023-01-20 22:07
I think it doesn't work... It will always empty itself
![5LbMCmlmz3](https://user-images.githubusercontent.com/54266662/213813735-ba124c51-f854-4ea8-bd4c-3bda37b0111a.gif)

**Comment by Tom4nt** [comment] 2023-01-21 00:07
Can you open the Dev Tools by pressing `Ctrl` `Shift` `I`? In the console tab, can you please check if there's an error there after you save the Settings and, if so, post the error here? Thank you.

**Comment by Noctabou** [comment] 2023-01-21 09:35
![VZaXH4wmxs](https://user-images.githubusercontent.com/54266662/213861046-a66eb4b3-39ff-4f75-8f5d-bfdb7de3c3e9.gif)
3 bundle.js:3163 
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at Keys.toKeyStringArray (bundle.js:3163:38)
    at set keys [as keys] (bundle.js:629:50)
    at SettingsModal.load (bundle.js:2461:41)

**Comment by Tom4nt** [comment] 2023-01-21 15:22
I was able to reproduce the issue and find the cause. 0.5.2 sets some fields as `null` but 0.6.1 does not support that. It will be fixed soon.
For now, to fix the settings, you can fill all the key fields with any keybind, and also the sound location. Then save, reopen the settings and delete the unwanted keybinds (right click). It should start working properly from that point on.

Thanks for the contribution!

**Closed** 2023-01-21 21:02 UTC
Labels: BUG
