### ISSUE TITLE
Singleton not initialized on new installation startup

### ISSUE THREAD

**Issue by jasonwynn10** [Tom4nt/Mega-Soundboard#46] opened 2023-01-17 01:21 UTC
*A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.*
Crash and error on first launch after installation
![image](https://user-images.githubusercontent.com/16521025/212788706-e501094e-7f76-494c-888e-b2720aab5b71.png)

*Steps to reproduce the behavior. This is important.*
Install using Installer 0.6.1
Run Mega Soundboard desktop shortcut

Environment:
 - OS and version: Windows 11 Pro 22H2
 - Mega Soundboard version: 0.6.1

**Comment by jasonwynn10** [comment] 2023-01-17 01:36
It seems to load up perfectly perfectly fine upon retrying, so I believe it's specific to the initial setup launch

**Comment by Tom4nt** [comment] 2023-01-17 01:52
Did you have v0.6.0 installed before trying to install v0.6.1? if so, I suspect the error message was caused by trying to open a second instance. v0.6.0 could still be running in the background even if you closed it with Alt+F4 because of the bug that was fixed in v0.6.1. Anyway, that error message should not appear in any case, so it's still a bug.

**Comment by Tom4nt** [comment] 2023-01-17 10:58
I tried reproducing the behavior by doing what you described, but I couldn't. The app opens automatically after installation so I don't know what you mean by running the desktop shortcut. After closing and reopening, it doesn't show the error. Also tried with v0.6.0 running but it prompts me to close it, so my assumption it the last comment was wrong.
If you could post more details on how to reproduce the bug, it would be very helpful. Thanks.

**Comment by jasonwynn10** [comment] 2023-01-20 01:35
There was no previous installation before installing 0.6.1. After installing though, the program did not appear to open automatically. I may have missed it if it was running without a UI or if it was delayed when I clicked on the icon to run it.

**Comment by Tom4nt** [comment] 2023-01-21 00:01
I successfully reproduced the bug in a machine that took a little bit more time to open the app after the installation. I'll look into it soon.
Thank you.

**Closed** 2023-01-21 21:02 UTC
Labels: BUG
