### ISSUE TITLE
Pausing sound only pauses primary output

### ISSUE THREAD

**Issue by JumpOff7667** [Tom4nt/Mega-Soundboard#48] opened 2023-05-19 11:52 UTC
Hi,
First of all thanks for this amazing soundboard app. I use it all the time.

Since the new update that adds the Seekbar, when I click on the pause button only the "Main device" gets paused, but not the secondary device, which is currently my earphones.

I don't know much about Electron and typescript, but I think that it is due to the fact that `Seekbar` can only get set a single `HTMLMediaElement` (which is the `HTMLAudioElement`) while it must have two `HTMLMediaElement`s: one for the "Main device" and another for the "Secondary device".

If you can have a look it would be great!

**Steps to reproduce:**

1. Set the "Main device" and the "Secondary device".
2. Create a sounds preset.
3. Add a sound to that preset.
4. Click on the newly added sound.
5. Press the pause button on the Seekbar.

**Environment:**
 - OS : Windows 10
 - Mega Soundboard 0.6.1

**Comment by Tom4nt** [comment] 2023-05-19 13:01
Thanks for the bug report!
You're right. I possibly forgot to control both media elements.
This will be fixed as soon as I can.

**Closed** 2023-05-19 22:03 UTC
Labels: BUG

**Comment by JumpOff7667** [comment] 2023-05-20 07:46
Thanks for the fix!
Unfortunately, another bug appeared. The Seekbar doesn't show the current progress of the sound, it is always stuck at the middle.

**Comment by Tom4nt** [comment] 2023-05-20 12:07
I can't reproduce that issue even if I click several times on the same/other sounds. I tried doing that for a few minutes and everything worked fine. Note that the Seekbar only appears if there's exactly one sound playing.
If you find more details about the issue, please provide them. Thank you.

**Comment by Tom4nt** [comment] 2023-05-20 16:02
I have found the cause of the issue and also 2 more in the process. They will all be fixed in the next patch.
