### ISSUE TITLE
Crash when Windows is closing

### ISSUE THREAD

**Issue by Noctabou** [Tom4nt/Mega-Soundboard#49] opened 2023-06-20 16:41 UTC
MegaSounboard is crashing when i shutdown my Windows, and it says that a stop point was accessed, error 0x80000003 at 0x00007FF70FA8C271
![image](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/0bd8f6f9-eac4-45ab-874c-f1a1265aa94c)

Theses are my settings
![image](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/6092e0fa-5059-45cb-983a-983de3a7c5b6)
I also configured my Windows to make MegaSounboard start on login
![image](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/86b1c79d-83f2-410d-94e7-3cab5a09934d)

Environment:
 - OS : Windows 11 22H2
 - Mega Soundboard version : 0.6.3

**Comment by Tom4nt** [comment] 2023-06-20 22:46
Thanks for the bug report!
Looks like it's an [electron bug](https://github.com/electron/electron/issues/34311).
As [this comment](https://github.com/electron/electron/issues/34311#issuecomment-1324283551) states, it should be fixed by not using `event.preventDefault()` in the `on('close')` event. I'm using `event.preventDefault()` because the app does some async work before shutting down. As a workaround, I may have to use synchronous alternatives. I'll investigate that soon.

Just a question: Does it prevent Windows from shutting down? Do you have to click "OK"?

**Comment by Noctabou** [comment] 2023-06-21 12:07
Yes, it prevents Windows from shutting down, i have to click OK, that's a bit annoying. Also, it's weird because it doesn't happen everytime.

**Comment by Tom4nt** [comment] 2023-06-23 22:55
I was unable to reproduce the bug, but I did what I said in my last comment. Can you use the patched version for a while to see if the bug still occurs (you can comment here if it does)? It's better to make sure it's fixed before making a release.
The fix is in the master branch. I've built a [binary](https://drive.google.com/file/d/1blloZL_80nPYFjfu2AJlpYzN3JuzuM-4/view?usp=sharing) so you don't have to, but you can build it yourself if you want.

**Comment by Noctabou** [comment] 2023-06-25 01:17
I trust you, and downloaded from the drive.
I just installed it, if it ever happen again, i will tell you here. Because i use it really often, let's say it's good in less than a month ?
Thank you for maintaining this app, it's one of my biggest finding on Github ^^

**Comment by Tom4nt** [comment] 2023-06-25 12:29
Sure, since only you know how often it happens, it's better for you to decide when it can be considered fixed or not.
And thank you for your words, they really motivate me to keep developing this app. :)

**Comment by Noctabou** [comment] 2023-06-27 19:45
![IMG_20230627_145435.jpg](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/f3d88a82-a978-459c-acd4-5c1cbb4bcb4a)

Guess who's back
Mhh but i'm not sure it's installed properly since there is no difference. I didn't uninstall + install the version you given me, i simply overrided the old installation. So i think it's installed properly but idk.
If you want, i can try next time it appears to click Debug instead of closing (i'm learning code so i think i can help a little)
Anyway, if you want to talk more about it, maybe you should add me on Discord (or something else, just to have instant chatting) _(same username everywhere)_

**Comment by Tom4nt** [comment] 2023-07-23 20:47
I still can't reproduce this, but [Noctabou](https://github.com/Noctabou) informed me that it is no longer happening. This issue will be reopened if it happens again.

**Closed by Tom4nt** 2023-07-23 20:47 UTC
Labels: BUG
